[package]
name = "tutorial13-terrain"
version = "0.1.0"
authors = ["Ben Hansen <bhbenjaminhansen@gmail.com>"]
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
app-surface.workspace = true
bytemuck = { workspace = true, features = ["derive"] }
cfg-if.workspace = true
glam.workspace = true
env_logger.workspace = true
instant.workspace = true
log.workspace = true
tobj = { workspace = true, features = ["async"] }
winit.workspace = true
wgpu.workspace = true
utils.workspace = true

[dependencies.image]
workspace = true
features = ["png", "jpeg"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
reqwest.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-time.workspace = true
web-sys = { workspace = true, features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }

[build-dependencies]
anyhow.workspace = true
fs_extra.workspace = true
glob.workspace = true
