[package]
name = "hdr"
version = "0.1.0"
authors = ["Ben Hansen (sotrh), Jinlei Li (jinleili0@outlook.com)"]
edition.workspace = true

[dependencies]
app-surface.workspace = true
bytemuck.workspace = true
env_logger.workspace = true
log.workspace = true
winit.workspace = true
wgpu = { workspace = true }
glam.workspace = true
utils.workspace = true
cfg-if = "1"
anyhow = "1.0"
tobj = { version = "3.2", features = ["async"] }
instant = "0.1"
# image 0.25.5 版本中, read_image_transform 被改成了私有方法, 所以使用 0.24 版本
image = { version = "=0.24.6", default-features = false, features = [
    "png",
    "jpeg",
    "hdr",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { workspace = true }
web-sys = { workspace = true, features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }

[build-dependencies]
anyhow.workspace = true
fs_extra.workspace = true
