[package]
name = "hilbert-curve"
version = "0.1.0"
authors = ["Jinlei Li <jinleili0@outlook.com>"]
edition.workspace = true
rust-version.workspace = true

[dependencies]
app-surface.workspace = true
bytemuck.workspace = true
env_logger.workspace = true
log.workspace = true
winit.workspace = true
wgpu.workspace = true
glam.workspace = true
utils.workspace = true