name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Alsa
        run: sudo apt-get install libasound2-dev
      - name: Build
        run: cargo build --verbose --workspace --exclude tutorial13-terrain
      - name: Run tests
        run: cargo test --verbose --workspace --exclude tutorial13-terrain
